# Generated by Django 6.0.8 on 2026-09-07 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('catalog', '0002_recordversion_source_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_kind', models.CharField(max_length=10)),
                ('actor_restrictions', models.JSONField(default=dict)),
                ('source_ids', models.JSONField(default=list)),
                ('filters', models.JSONField(default=dict)),
                ('format', models.CharField(choices=[('jsonl', 'JSONL'), ('csv', 'CSV')], max_length=5)),
                ('fields', models.JSONField(default=list)),
                ('cursor', models.TextField()),
                ('snapshot', models.PositiveBigIntegerField()),
                ('status', models.CharField(default='queued', max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('max_credits', models.PositiveBigIntegerField()),
                ('credits', models.PositiveBigIntegerField(default=0)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('byte_count', models.PositiveIntegerField(default=0)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.servicekey')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.dataset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ExportChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('rows', models.PositiveIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='exports.exportjob')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'page'), name='exports_unique_page')],
            },
        ),
    ]
