# Generated by Django 6.0.8 on 2026-09-07 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=200)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exports.exportjob')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'request_id'), name='exports_unique_request')],
            },
        ),
    ]
