# Generated by Django 6.0.3 on 2026-03-31 18:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('clerk_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('plan', models.CharField(default='free', max_length=32)),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('key_prefix', models.CharField(max_length=20)),
                ('environment', models.CharField(choices=[('live', 'Live'), ('test', 'Test')], max_length=10)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.account')),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='SyncBatchRecord',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_sequence', models.IntegerField()),
                ('last_sequence', models.IntegerField()),
                ('chain_hash', models.CharField(max_length=128)),
                ('content_hash', models.CharField(max_length=128)),
                ('signature', models.CharField(max_length=128)),
                ('entry_count', models.IntegerField()),
                ('sdk_version', models.CharField(max_length=20)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_batches', to='core.account')),
            ],
            options={
                'db_table': 'sync_batch_records',
                'indexes': [models.Index(fields=['account', 'last_sequence'], name='sync_batch__account_25f4c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncedAuditEntry',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(db_index=True)),
                ('actor_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=128)),
                ('target_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('hash', models.CharField(max_length=128)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=128)),
                ('scope_id', models.CharField(blank=True, max_length=64, null=True)),
                ('parent_trace_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('batch_id', models.CharField(db_index=True, max_length=64)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='core.account')),
            ],
            options={
                'db_table': 'synced_audit_entries',
                'indexes': [models.Index(fields=['account', 'actor_id'], name='synced_audi_account_260b0e_idx'), models.Index(fields=['account', 'target_type', 'target_id'], name='synced_audi_account_f806a4_idx'), models.Index(fields=['account', 'timestamp'], name='synced_audi_account_7eb7cf_idx')],
                'unique_together': {('account', 'sequence')},
            },
        ),
    ]
