# Generated by Django 6.0.3 on 2026-03-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='scoped_object_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
