# Generated by Django 6.0.3 on 2026-03-31 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_permissions(apps, schema_editor):
    """Seed the 14 platform permissions."""
    from plane.core.defaults import PERMISSIONS
    Permission = apps.get_model("core", "Permission")
    for perm_id, name, category, description in PERMISSIONS:
        Permission.objects.get_or_create(
            id=perm_id,
            defaults={"name": name, "category": category, "description": description},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apikey_scoped_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('scoped_scope_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='plan',
        ),
        migrations.AddField(
            model_name='apikey',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.application'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('clerk_org_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('is_personal', models.BooleanField(default=False)),
                ('plan', models.CharField(default='free', max_length=32)),
                ('scoped_principal_id', models.CharField(blank=True, max_length=64, null=True)),
                ('scoped_scope_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to='core.account')),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.organization'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('scoped_rule_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.organization')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.role')),
            ],
            options={
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='core.RolePermission', to='core.permission'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('organization', 'slug')},
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('clerk_membership_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('scoped_membership_id', models.CharField(blank=True, max_length=64, null=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.role')),
            ],
            options={
                'db_table': 'memberships',
                'unique_together': {('organization', 'account')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('organization', 'name')},
        ),
        migrations.RunPython(seed_permissions, migrations.RunPython.noop),
    ]
