# Generated by Django 6.0.3 on 2026-04-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_application_permission_remove_account_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_status',
            field=models.CharField(default='active', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
