# Generated by Django 6.0.3 on 2026-04-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_billing_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['account', 'is_active'], name='api_keys_account_41a5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['application', 'is_active', 'environment'], name='api_keys_applica_fc1adc_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['plan', 'billing_status'], name='organizatio_plan_da788a_idx'),
        ),
    ]
