# Generated by Django 6.0.3 on 2026-04-03 02:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_apikey_signing_key_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMembership',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('environment', models.CharField(blank=True, choices=[('test', 'Test'), ('live', 'Live')], max_length=10, null=True)),
                ('scoped_membership_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_memberships', to='core.application')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_memberships', to='core.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_memberships', to='core.role')),
            ],
            options={
                'db_table': 'app_memberships',
                'indexes': [models.Index(fields=['application', 'environment'], name='app_members_applica_b3c60f_idx')],
                'unique_together': {('membership', 'application', 'environment')},
            },
        ),
    ]
