# Generated by Django 6.0.3 on 2026-04-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='overage_since',
            field=models.DateTimeField(blank=True, help_text='When the org first exceeded plan limits. NULL = within limits.', null=True),
        ),
    ]
