# Generated by Django 6.0.3 on 2026-03-31 18:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('max_objects', models.IntegerField()),
                ('max_principals', models.IntegerField()),
                ('audit_retention_days', models.IntegerField()),
                ('min_sync_interval_seconds', models.IntegerField()),
                ('price_cents_monthly', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('peak_objects', models.IntegerField(default=0)),
                ('peak_principals', models.IntegerField(default=0)),
                ('total_audit_entries', models.IntegerField(default=0)),
                ('finalized', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='core.account')),
            ],
            options={
                'db_table': 'billing_periods',
                'indexes': [models.Index(fields=['account', 'period_start'], name='billing_per_account_559b0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active_objects', models.IntegerField()),
                ('active_principals', models.IntegerField()),
                ('active_scopes', models.IntegerField()),
                ('audit_entries_synced', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='core.account')),
            ],
            options={
                'db_table': 'usage_snapshots',
                'indexes': [models.Index(fields=['account', 'recorded_at'], name='usage_snaps_account_78d981_idx')],
            },
        ),
    ]
