# Generated by Django 6.0.3 on 2026-03-31 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0004_application_permission_remove_account_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingperiod',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='core.organization'),
        ),
        migrations.AddField(
            model_name='usagesnapshot',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='core.application'),
        ),
        migrations.AddField(
            model_name='usagesnapshot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='core.organization'),
        ),
    ]
