# Generated by Django 6.0.3 on 2026-04-01 00:19

from django.db import migrations, models


def seed_plans(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.update_or_create(id="free", defaults={
        "name": "Free",
        "max_objects": 1000,
        "max_principals": 50,
        "audit_retention_days": 7,
        "min_sync_interval_seconds": 3600,
        "price_cents_monthly": 0,
        "included_objects": 1000,
        "included_principals": 50,
        "overage_per_object_cents": 0,
        "overage_per_principal_cents": 0,
    })
    Plan.objects.update_or_create(id="pro", defaults={
        "name": "Pro",
        "max_objects": 100000,
        "max_principals": 10000,
        "audit_retention_days": 90,
        "min_sync_interval_seconds": 60,
        "price_cents_monthly": 4900,
        "included_objects": 10000,
        "included_principals": 500,
        "overage_per_object_cents": 1,
        "overage_per_principal_cents": 5,
    })


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingperiod_organization_usagesnapshot_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='included_objects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_principals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='overage_per_object_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='overage_per_principal_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_base_price_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_object_price_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_principal_price_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(seed_plans, migrations.RunPython.noop),
    ]
