# Generated by Django 6.0.3 on 2026-04-02 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_included_objects_plan_included_principals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=128)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'stripe_events',
            },
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='close_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='close_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
