# Generated by Django 6.0.8 on 2026-09-07 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='access.workspace')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='free', max_length=30)),
                ('period_start', models.DateTimeField(null=True)),
                ('period_end', models.DateTimeField(null=True)),
                ('allowance_start', models.DateTimeField(null=True)),
                ('overage_enabled', models.BooleanField(default=False)),
                ('spend_cap_cents', models.PositiveIntegerField(default=0)),
                ('metered_item_active', models.BooleanField(default=False)),
                ('checkout_generation', models.UUIDField(default=uuid.uuid4)),
                ('checkout_session_id', models.CharField(blank=True, max_length=120)),
                ('checkout_url', models.URLField(blank=True, max_length=2000)),
                ('checkout_expires_at', models.DateTimeField(null=True)),
                ('reconciled_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_slug', models.CharField(max_length=100)),
                ('request_id', models.CharField(max_length=200)),
                ('fingerprint', models.CharField(max_length=128)),
                ('response', models.JSONField()),
                ('records', models.PositiveIntegerField()),
                ('credits', models.PositiveBigIntegerField()),
                ('overage_credits', models.PositiveBigIntegerField(default=0)),
                ('pricing_cents_per_10000', models.PositiveIntegerField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('event_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeterOutbox',
            fields=[
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='commerce.delivery')),
                ('customer_id', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField(null=True)),
                ('next_attempt_at', models.DateTimeField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['workspace', 'created_at'], name='commerce_usage_period'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_id'), name='commerce_unique_delivery'),
        ),
    ]
