# Generated by Django 6.0.8 on 2026-09-07 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('expected_credits', models.PositiveBigIntegerField()),
                ('remote_credits', models.DecimalField(decimal_places=6, max_digits=24)),
                ('status', models.CharField(max_length=20)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'start_at', 'end_at'), name='commerce_unique_reconciliation')],
            },
        ),
    ]
