# Generated by Django 6.0.8 on 2026-09-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('commerce', '0002_meterreconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overage_enabled', models.BooleanField()),
                ('spend_cap_cents', models.PositiveIntegerField()),
                ('overage_cents_per_10000', models.PositiveIntegerField()),
                ('policy_version', models.CharField(default='marketplace-v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.identity')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.workspace')),
            ],
        ),
    ]
