# Generated by Django 6.0.8 on 2026-09-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_billingconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='cancellation_completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='cancellation_requested_at',
            field=models.DateTimeField(null=True),
        ),
    ]
