# Generated by Django 6.0.8 on 2026-09-07 17:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('is_operator', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My workspace', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='workspace', to='access.identity')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=18)),
                ('scopes', models.JSONField(default=list)),
                ('dataset_slugs', models.JSONField(default=list)),
                ('source_slugs', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='access.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_hash', models.CharField(max_length=64, unique=True)),
                ('user_code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('scopes', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('last_poll_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access.workspace')),
            ],
        ),
    ]
