# Generated by Django 6.0.8 on 2026-09-07 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityEvent',
            fields=[
                ('message_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JWKSnapshot',
            fields=[
                ('issuer', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('document', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(null=True)),
                ('last_attempt_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevokedSession',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('revoked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='identity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
