# Generated by Django 6.0.8 on 2026-09-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=200)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='complete', max_length=12)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('withdrawn', 'withdrawn')], default='draft', max_length=12)),
                ('credits_per_record', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('credits_per_record__gte', 1)), name='catalog_positive_price')],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='catalog.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('fields', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemas', to='catalog.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('observed_at', models.DateTimeField()),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=2000)),
                ('content_hash', models.CharField(max_length=64)),
                ('tombstone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalog.ingestionbatch')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalog.record')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.schemaversion')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2000)),
                ('attribution', models.TextField(blank=True)),
                ('license_url', models.URLField(blank=True, max_length=2000)),
                ('rights_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('blocked', 'blocked')], default='pending', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='catalog.dataset')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='catalog.schemaversion')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='catalog.source'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.source'),
        ),
        migrations.AddConstraint(
            model_name='schemaversion',
            constraint=models.UniqueConstraint(fields=('dataset', 'version'), name='catalog_unique_schema'),
        ),
        migrations.AddConstraint(
            model_name='schemaversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='catalog_positive_schema'),
        ),
        migrations.AddIndex(
            model_name='recordversion',
            index=models.Index(fields=['record', '-id'], name='catalog_record_revision'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('dataset', 'slug'), name='catalog_unique_source'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='catalog_unique_record'),
        ),
        migrations.AddConstraint(
            model_name='ingestionbatch',
            constraint=models.UniqueConstraint(fields=('source', 'idempotency_key'), name='catalog_unique_batch'),
        ),
    ]
