# Generated by Django 6.0.8 on 2026-09-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordversion',
            name='source_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
