# Generated by Django 6.0.8 on 2026-09-07 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_recordversion_source_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='rights_status',
            field=models.CharField(choices=[('pending', 'pending'), ('evaluation', 'evaluation'), ('approved', 'approved'), ('blocked', 'blocked')], default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('summary', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_runs', to='catalog.source')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_allowed_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ingestionbatch')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection_state', to='catalog.source')),
            ],
        ),
    ]
